# Preprocessing

From EDA, we understood that:
- We have duplicated rows on customer_basket
- When the same items are bought in two different instances, these are attributed different invoices. Hence, invoice_id cannot be the index column
- 32% have a missing loyalty_card_number (probably don't have one)
- percentage_of_products_bought_promotion is a percentage with negative values
#
From EDA, we also noted that there are no really highly correlated values, hence nothing should be dropped.

In [6]:
import numpy as np
import pandas as pd
from datetime import datetime # to get the current datetime

import matplotlib.pyplot as plt # to make plots (histograms, etc...)
import seaborn as sns
import plotly.express as px
import folium
import branca.colormap as cm  # for color mapping based on data values

import ast # transform the strings into a list

In [7]:
# Show all columns when displaying a DataFrame
pd.set_option('display.max_columns', None)

# Optional: Also show more rows if needed
pd.set_option('display.max_rows', 100)

# shows all columns
pd.set_option("display.max_columns", None)

# prevents wrapping
pd.set_option("display.width", 1000)

pd.set_option('display.max_colwidth', None)

### 1. Import and Preview Datasets ###

In [9]:
customer_basket = pd.read_csv('../data/raw/customer_basket.csv')
customer_info = pd.read_csv('../data/raw/customer_info.csv', index_col=["customer_id"])

customer_info = customer_info.drop("Unnamed: 0", axis='columns')

In [10]:
customer_basket.head(5)

   invoice_id                                                                                                                                                                                           list_of_goods  customer_id
0     5062209  ['megaman zero 3', 'energy bar', 'pokemon violet', 'airpods', 'fresh bread', 'pancakes', 'brownies', 'energy drink', 'champagne', 'red wine', 'bluetooth headphones', 'protein bar', 'metroid fusion']         4925
1     4272512                     ['black beer', 'bramble', 'laptop', 'pokemon violet', 'airpods', 'gadget for tiktok streaming', 'ring light', 'ratchet & clank', 'pancakes', 'energy drink', 'gums', 'protein bar']        19046
2     7121052                                                          ['soup', 'shallot', 'cake', 'fresh bread', 'cream', 'carrots', 'babies food', 'ham', 'cookies', 'salad', 'tomato sauce', 'cooking oil', 'tea']        10318
3     5847748                                                   ['soup', 'cooking oil', 'cereals', 'oil', 'dog food', 'deodorant', 'tomatoes', 'yogurt cake', 'pet food', 'salmon', 'olive oil', 'fresh tuna', 'tea']        27283
4     6336114                          ['eggplant', 'mint green tea', 'oil', 'bacon', 'toilet paper', 'shrimp', 'brownies', 'pancakes', 'champagne', 'spinach', 'cologne', 'chicken', 'barbecue sauce', 'fresh tuna']        16072

In [11]:
customer_info.head(5)

                 customer_name customer_gender   customer_birthdate  kids_home  teens_home  number_complaints  distinct_stores_visited  lifetime_spend_groceries  lifetime_spend_electronics  typical_hour  lifetime_spend_vegetables  lifetime_spend_nonalcohol_drinks  lifetime_spend_alcohol_drinks  lifetime_spend_meat  lifetime_spend_fish  lifetime_spend_hygiene  lifetime_spend_videogames  lifetime_spend_petfood  lifetime_total_distinct_products  percentage_of_products_bought_promotion  year_first_transaction  loyalty_card_number   latitude  longitude
customer_id
29930              April Clark          female  01/15/1972 02:27 PM        2.0         2.0                1.0                      4.0                    7789.0                      5601.0          13.0                      726.0                             962.0                         1213.0               1598.0               1894.0                   457.0                      412.0                   428.0                             386.0                                 0.158741                  2018.0                  NaN  38.721807  -9.125534
6813         Bsc. Paul Ketchum            male  07/31/1944 10:53 AM        0.0         1.0                0.0                      4.0                    8653.0                        35.0          14.0                      792.0                             102.0                          104.0                741.0                346.0                   394.0                       75.0                   226.0                              73.0                                 1.227890                  2013.0             971840.0  38.734668  -9.163533
39451             Mary Downing          female  11/13/1989 02:11 PM        2.0         3.0                0.0                      7.0                   15605.0                      4275.0          14.0                     1585.0                             980.0                         1872.0               1323.0               1971.0                   920.0                      335.0                   192.0                             319.0                                 0.101598                  2011.0                  NaN  38.787126  -9.147077
21557             Manuel Kueny            male  08/09/1976 06:23 AM        0.0         0.0                1.0                      1.0                   13440.0                     16366.0          14.0                       28.0                             269.0                         1855.0                939.0                785.0                   139.0                      679.0                   270.0                             221.0                                 0.259943                  2009.0                  NaN  38.741816  -9.159700
16415        Phd. Curtis Tharp            male  07/11/1966 08:12 AM        1.0         1.0                1.0                      5.0                   49250.0                      3197.0          14.0                      258.0                             726.0                          547.0                983.0               1492.0                  1046.0                      112.0                   144.0                             244.0                                 0.317822                  2012.0             925367.0  38.785921  -9.149221

In [12]:
customer_basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   invoice_id     100000 non-null  int64
 1   list_of_goods  100000 non-null  object
 2   customer_id    100000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 2.3+ MB

In [13]:
customer_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34060 entries, 29930 to 22050
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_name                            34060 non-null  object
 1   customer_gender                          34060 non-null  object
 2   customer_birthdate                       33719 non-null  object
 3   kids_home                                33311 non-null  float64
 4   teens_home                               33277 non-null  float64
 5   number_complaints                        33038 non-null  float64
 6   distinct_stores_visited                  33379 non-null  float64
 7   lifetime_spend_groceries                 34060 non-null  float64
 8   lifetime_spend_electronics               34060 non-null  float64
 9   typical_hour                             32698 non-null  float64
 10  lifetime_spend_vegetables                33038 non-null  float64
 11  lifetime_spend_nonalcohol_drinks         34060 non-null  float64
 12  lifetime_spend_alcohol_drinks            33379 non-null  float64
 13  lifetime_spend_meat                      34060 non-null  float64
 14  lifetime_spend_fish                      32357 non-null  float64
 15  lifetime_spend_hygiene                   34060 non-null  float64
 16  lifetime_spend_videogames                34060 non-null  float64
 17  lifetime_spend_petfood                   34060 non-null  float64
 18  lifetime_total_distinct_products         34060 non-null  float64
 19  percentage_of_products_bought_promotion  34060 non-null  float64
 20  year_first_transaction                   34060 non-null  float64
 21  loyalty_card_number                      23152 non-null  float64
 22  latitude                                 34060 non-null  float64
 23  longitude                                34060 non-null  float64
dtypes: float64(21), object(3)
memory usage: 6.5+ MB

Because the datasets are rather small and mostly numerical, we don't see the need to adapt the data types

### 2. Data Cleaning ###
Dealing with the duplicates, missing values and noise

#### 2.1) Duplicates

#### 2.1.1) For customer_basket

In [20]:
customer_basket.duplicated().sum()

np.int64(0)

On a first look, it seems there are no duplicated rows...

In [21]:
customer_basket["invoice_id"].is_unique

False

In [22]:
customer_basket["customer_id"].is_unique

False

With this, we may conclude that, although there are no duplicated rows, some refer to the same customer making different purchases (identical *customer_id*), while others reflect different customers buying the same set of items (identical *invoice_id*).

#### 2.1.2) For customer_info

In [23]:
customer_basket.duplicated().sum()

np.int64(0)

Here, because we managed to set *customer_id* as an index, and also due to the last block of code showing no repeated rows, we may conclude there aren't any duplicates in the *customer_info* dataset

#### 2.2) Missing Values / Imputation

#### 2.2.1) For customer_basket

In [26]:
missing_customer_basket = pd.DataFrame({
    'Missing Count': customer_basket.isnull().sum(),
    'Missing %': round(customer_basket.isnull().mean() * 100, 2)
})
missing_customer_basket

               Missing Count  Missing %
invoice_id                 0        0.0
list_of_goods              0        0.0
customer_id                0        0.0

Great! We have no missing values in the *customer_basket* dataset.

#### 2.2.2) For customer_info

In [27]:
missing_customer_info = pd.DataFrame({
    'Missing Count': customer_info.isnull().sum(),
    'Missing %': round(customer_info.isnull().mean() * 100, 2)
})
missing_customer_info

                                         Missing Count  Missing %
customer_name                                        0       0.00
customer_gender                                      0       0.00
customer_birthdate                                 341       1.00
kids_home                                          749       2.20
teens_home                                         783       2.30
number_complaints                                 1022       3.00
distinct_stores_visited                            681       2.00
lifetime_spend_groceries                             0       0.00
lifetime_spend_electronics                           0       0.00
typical_hour                                      1362       4.00
lifetime_spend_vegetables                         1022       3.00
lifetime_spend_nonalcohol_drinks                     0       0.00
lifetime_spend_alcohol_drinks                      681       2.00
lifetime_spend_meat                                  0       0.00
lifetime_spend_fish                               1703       5.00
lifetime_spend_hygiene                               0       0.00
lifetime_spend_videogames                            0       0.00
lifetime_spend_petfood                               0       0.00
lifetime_total_distinct_products                     0       0.00
percentage_of_products_bought_promotion              0       0.00
year_first_transaction                               0       0.00
loyalty_card_number                              10908      32.03
latitude                                             0       0.00
longitude                                            0       0.00

We will use K Nearest Neighbours imputation to replace these missing values. Thankfully, *customer_gender* has no missing values so we don't need to encode it now. Furthermore, it may not make much sense to use knn for *loyalty_card_number* but this column will later be removed.

In [28]:
## we need to temporarly scale the data to apply knn.

#### 2.3) Noise

As we saw in the EDA, some values are impossible to achieve, namely negative numbers in <i>percentage_of_products_bought_promotion</i>. Thus, we will assume these values to be zero and replace them.

In [14]:
# replace the percentage_of_products_bought_promotion below 0 with 0

import numpy as np

customer_info["percentage_of_products_bought_promotion"] = np.where(
    customer_info["percentage_of_products_bought_promotion"] < 0,
    0,
    customer_info["percentage_of_products_bought_promotion"]
)

## STUFF TO DO ##

- We have duplicate rows on customer_basket

- Regarding the customer_basket dataset, when the same items are bought in two different instances, these are attributed different invoices. Thus we cannot make invoice_id our index column

- 32% of customers have a missing value at loyalty_card_number, meaning they probably don't have one.

- percentage_of_products_bought_promotion is a percentage, yet has negative values (DONE)

- Permanently drop the **customer_name**, **loyalty_card_number** and the **year_first_transaction** columns, as they're either irrelevant, or correlated with other variables

1. Import and preview Datasets (DONE)

2. Data Cleaning
- Duplicates in customer_basket will not be deleted
- Missing values on customer_info (loyalty_card_number)

3. Feature Adjustments
- We will add and then remove columns
- We will evaluate whether highly correlated variables will be kept
- label encoding for the **customer_gender** variable

4. Outlier detection and replacement
- DBSCAN

5. Scaling

6. Data exportation